### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by Rachel-Norman** [Rachel-Norman/no-sketch-no-grid#1]
@wendywarren

[mockup.pdf](https://github.com/Rachel-Norman/no-sketch-no-grid/files/8344901/mockup.pdf)
[mockup-grid.pdf](https://github.com/Rachel-Norman/no-sketch-no-grid/files/8344902/mockup-grid.pdf)

body - contains all content
header - website masthead
h1 - most important content
img - images
h2 - content heading/sub-heading
p - paragraph of text
main - primary content of the page
figure - annotated images
figcaption - adding an annotation to the figure 
h3 - content heading/sub-heading
dl - description list
dt - description title
dd - description definition

**Comment by wendywarren** [comment]
Hi @Rachel-Norman,

Overall good job deciding proper html elements. I'm sure you noticed once you started to code the page that the header was just the h1 and all other content was within the main; within the grid of two rows.

Besides the h3 actually being an h2, you did an excellent job with the bottom portion.

Let me know if you have any questions.

Wendy
